In [4]:
import numpy as np

In [5]:
list1= [1,2,3]
print(list1)

[1, 2, 3]


In [6]:
array1ay1=np.array1ay(list1)

In [7]:
print(array1ay1)

[1 2 3]


In [8]:
array2=np.array([[1,2,3],[4,5,6]])   ##CONVERTS INTO A MULTIDIMENSTIONAL LIST

In [9]:
print(array2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(array2.shape) ###IT IS ROW,COLUMN (DIMENSIONS OF THE MATRIX)

(2, 3)


In [11]:
print(array2.dtype)  #type of data in the array

int64


In [12]:
array3 = np.array([0.2,0.3,0.4])
print(array3.dtype)


float64


In [13]:
print(array1.ndim) #ndim gives number of rows/dimension of array

1


In [14]:
print(array2.ndim)

2


In [15]:
print(array1.itemsize) #number of elements in the array

8


In [16]:
print(array3.itemsize) #number of bytes for an element in the array (int 4, float 8, etc).

8


In [17]:
#you can declare dtype = int32 (then fo reach element itll be 4), int64 (each element itll be 8)

In [18]:
###ASSIGNMENT RA2211003012017 JAYASHREE MANIGANDAN - DATA SCIENCE

In [19]:
#INSTALLING THE NUMPY PACKAGE
!pip install numpy

In [20]:
#PRINTING THE VERSION OF NUMPY
!pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [21]:
#IMPORTING
import numpy as np

In [22]:
#CREATING THE 3D AND 4D LISTS
list_1 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

In [23]:
list_2 = [[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]], [[[9.0, 10.0], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16.0]]], 
          [[[17.0, 18.0], [19.0, 20.0]], [[21.0, 22.0], [23.0, 24.0]]]]

In [24]:
#CREATING THE ARRAYS
array1=np.array(list_1)

In [25]:
array2=np.array(list_2)

In [26]:
#AXIS
print("Array 1 has the following axes: ")
for i in range(len(array1.shape)):
    print(f"Axis {i}: Size {array1.shape[i]}")

print("Array 2 has the following axes: ")
for i in range(len(array2.shape)):
    print(f"Axis {i}: Size {array2.shape[i]}")

Array 1 has the following axes: 
Axis 0: Size 3
Axis 1: Size 3
Axis 2: Size 3
Array 2 has the following axes: 
Axis 0: Size 3
Axis 1: Size 2
Axis 2: Size 2
Axis 3: Size 2


In [27]:
#SHAPE
print("The shape of array 1 is: ",array1.shape)
print("The shape of array 2 is: ",array2.shape)

The shape of array 1 is:  (3, 3, 3)
The shape of array 2 is:  (3, 2, 2, 2)


In [28]:
#NDIM and RANK
print("The rank and dimension of array 1 is: ",array1.ndim)
print("The rank and dimension of array 2 is: ",array2.ndim)

The rank and dimension of array 1 is:  3
The rank and dimension of array 2 is:  4


In [29]:
#DATATYPE
print("The datatype of array1 is: ",array1.dtype)
print("The datatype of array2 is: ",array2.dtype)

The datatype of array1 is:  int64
The datatype of array2 is:  float64


In [30]:
#DATA ATTRIBUTE 
print("The data attribute of array 1 is: ",array1.data)
print("The data attribute of array 2 is: ",array2.data)

The data attribute of array 1 is:  <memory at 0x0000017095B84F40>
The data attribute of array 2 is:  <memory at 0x000001709545A740>


In [31]:
#SIZE
print("The size of array 1 is: ",array1.size)
print("The size of array 2 is: ",array2.size)

The size of array 1 is:  27
The size of array 2 is:  24


In [32]:
#ITEMSIZE
print("The itemsize is: ",array1.itemsize)
print("The itemsize is: ",array2.itemsize)

The itemsize is:  8
The itemsize is:  8


In [33]:
!pip install cartopy

In [34]:
!pip show cartopy

Name: Cartopy
Version: 0.24.1
Summary: A Python library for cartographic visualizations with Matplotlib
Home-page: 
Author: UK Met Office
Author-email: 
License: BSD 3-Clause License

Copyright (c) Crown and Cartopy contributors.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRI

In [37]:
###Operation - 1 ARRAY INDEXING

print(array1)
print(array1[0])
print(array1[1]+array1[2])

print('2nd element on 1st row: ', array1[0, 1])
print('1st element in 1st row: ', array1[0, 0, 0])
print('4th element in 2nd row: ', array1[0, 1, 0])
print('5th element in 2nd row: ', array1[0, 1, 1])
print('6th element in 2nd row: ', array1[0, 1, 2])

##Negative indexing
print(array2)
print('Last element from 1st dim: ', array2[0, -1])
print('Last element from 2nd dim: ', array2[1, -1])



[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[29 31 33]
 [35 37 39]
 [41 43 45]]
2nd element on 1st row:  [4 5 6]
1st element in 1st row:  1
4th element in 2nd row:  4
5th element in 2nd row:  5
6th element in 2nd row:  6
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]


 [[[17. 18.]
   [19. 20.]]

  [[21. 22.]
   [23. 24.]]]]
Last element from 1st dim:  [[5. 6.]
 [7. 8.]]
Last element from 2nd dim:  [[13. 14.]
 [15. 16.]]


In [41]:
###Operation 2 Array slicing

import numpy as np
arr = array1

print("\nSlice elements from index 1 to index 2 from the array:",arr[1:2])
print("Slice elements from index 1 to index 3 from the array:",arr[1:3])
print("Slice elements from index 1 to index 4 from the array:",arr[1:4])

print("\nSlice elements from index 0 to the end of the array:",arr[0:])
print("Slice elements from index 1 to the end of the array:",arr[1:])
print("Slice elements from index 2 to the end of the array:",arr[2:])

print("\nSlice elements from the beginning to index 0 (not included):",arr[:0])
print("Slice elements from the beginning to index 1 (not included):",arr[:1])
print("Slice elements from the beginning to index 2 (not included):",arr[:2])
print("Slice elements from the beginning to index 3 (not included):",arr[:3])


###Negative Slicing-Use the minus operator to refer to an index from the end:
print("\nSlice from the index 3 from the end to index 1 from the end:",arr[-3:-1])


###STEP-Use the step value to determine the step of the slicing:
print("\nReturn every other element from index 1 to index 5:",arr[1:5:2])
print("Return every other element from the entire array:", arr[::2])



Slice elements from index 1 to index 2 from the array: [[[10 11 12]
  [13 14 15]
  [16 17 18]]]
Slice elements from index 1 to index 3 from the array: [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Slice elements from index 1 to index 4 from the array: [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Slice elements from index 0 to the end of the array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Slice elements from index 1 to the end of the array: [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Slice elements from index 2 to the end of the array: [[[19 20 21]
  [22 23 24]
  [25 26 27]]]

Slice elements from the beginning to index 0 (not included): []
Slice elements from the beginning to index 1 (not included): [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Slice elements from the beginning to index 2 (not included): [[[ 

In [47]:
###Operation 3 Array iteration

array_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in array_3:
  print("Iterate on the elements of the following 3-D array:",x)
for x in array_3:
    for y in x:
        for z in y:
            print(z)

Iterate on the elements of the following 3-D array: [[1 2 3]
 [4 5 6]]
Iterate on the elements of the following 3-D array: [[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


In [48]:
array_4 = np.array([[[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]], [[[9.0, 10.0], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16.0]]], 
          [[[17.0, 18.0], [19.0, 20.0]], [[21.0, 22.0], [23.0, 24.0]]]])
for x in array_4:
    for y in x:
        for z in y:
            for j in z:
                print(j)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
13.0
14.0
15.0
16.0
17.0
18.0
19.0
20.0
21.0
22.0
23.0
24.0


In [49]:
###Operation 4 - Array copying
print(array_4)
x1 = array_4.copy()
print(x1)

[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]


 [[[17. 18.]
   [19. 20.]]

  [[21. 22.]
   [23. 24.]]]]
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]


 [[[17. 18.]
   [19. 20.]]

  [[21. 22.]
   [23. 24.]]]]


In [60]:
# Creating a 3D array
array_3d = np.random.randint(1, 100, (3, 3, 3))
# Creating a 4D array
array_4d = np.random.randint(1, 100, (2, 3, 3, 3))

# Sorting a numpy array
sorted_3d = np.sort(array_3d, axis=-1)
sorted_4d = np.sort(array_4d, axis=-1)

print("Original 3D Array:\n", array_3d)
print("Sorted 3D Array:\n", sorted_3d)

print("Original 4D Array:\n", array_4d)
print("Sorted 4D Array:\n", sorted_4d)


Original 3D Array:
 [[[37 79 21]
  [43 83 63]
  [83  5 36]]

 [[77 25  5]
  [22  2 90]
  [15 54 86]]

 [[68 45 70]
  [43  4 71]
  [64  6  6]]]
Sorted 3D Array:
 [[[21 37 79]
  [43 63 83]
  [ 5 36 83]]

 [[ 5 25 77]
  [ 2 22 90]
  [15 54 86]]

 [[45 68 70]
  [ 4 43 71]
  [ 6  6 64]]]
Original 4D Array:
 [[[[44 82 62]
   [ 4 49 42]
   [ 9 72 78]]

  [[37  6 71]
   [12 75 66]
   [23 79 78]]

  [[42 74 94]
   [61 66 58]
   [37 57 44]]]


 [[[15 60 31]
   [54  4 72]
   [16 64 26]]

  [[ 5 79 35]
   [52 32 20]
   [23 88 53]]

  [[71 54  2]
   [84 90 36]
   [10 84 33]]]]
Sorted 4D Array:
 [[[[44 62 82]
   [ 4 42 49]
   [ 9 72 78]]

  [[ 6 37 71]
   [12 66 75]
   [23 78 79]]

  [[42 74 94]
   [58 61 66]
   [37 44 57]]]


 [[[15 31 60]
   [ 4 54 72]
   [16 26 64]]

  [[ 5 35 79]
   [20 32 52]
   [23 53 88]]

  [[ 2 54 71]
   [36 84 90]
   [10 33 84]]]]


In [61]:
# Searching a numpy array (where and searchsorted)
search_val = 50
indices_3d = np.where(array_3d > search_val)
indices_4d = np.where(array_4d > search_val)

# Using searchsorted (for 1D slices of 3D and 4D arrays)
sorted_1d_3d = np.sort(array_3d.flatten())
search_index_3d = np.searchsorted(sorted_1d_3d, search_val)

sorted_1d_4d = np.sort(array_4d.flatten())
search_index_4d = np.searchsorted(sorted_1d_4d, search_val)

print("Indices of elements > 50 in 3D Array:\n", indices_3d)
print("Searchsorted index in 3D array:\n", search_index_3d)
print("Indices of elements > 50 in 4D Array:\n", indices_4d)
print("Searchsorted index in 4D array:\n", search_index_4d)


Indices of elements > 50 in 3D Array:
 (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 1, 2, 0, 1, 2, 2, 0, 0, 1, 2]), array([1, 1, 2, 0, 0, 2, 1, 2, 0, 2, 2, 0]))
Searchsorted index in 3D array:
 15
Indices of elements > 50 in 4D Array:
 (array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]), array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1,
       1, 2, 2, 2, 2, 2]), array([0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 2,
       2, 0, 0, 1, 1, 2]), array([1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 0, 1, 2, 1, 1, 0, 2, 1, 1, 0, 1,
       2, 0, 1, 0, 1, 1]))
Searchsorted index in 4D array:
 26


In [62]:

# Splitting a numpy array
split_3d = np.split(array_3d, 3, axis=0)
split_4d = np.split(array_4d, 2, axis=0)
print("Split 3D Array:\n", split_3d)
print("Split 4D Array:\n", split_4d)

Split 3D Array:
 [array([[[37, 79, 21],
        [43, 83, 63],
        [83,  5, 36]]], dtype=int32), array([[[77, 25,  5],
        [22,  2, 90],
        [15, 54, 86]]], dtype=int32), array([[[68, 45, 70],
        [43,  4, 71],
        [64,  6,  6]]], dtype=int32)]
Split 4D Array:
 [array([[[[44, 82, 62],
         [ 4, 49, 42],
         [ 9, 72, 78]],

        [[37,  6, 71],
         [12, 75, 66],
         [23, 79, 78]],

        [[42, 74, 94],
         [61, 66, 58],
         [37, 57, 44]]]], dtype=int32), array([[[[15, 60, 31],
         [54,  4, 72],
         [16, 64, 26]],

        [[ 5, 79, 35],
         [52, 32, 20],
         [23, 88, 53]],

        [[71, 54,  2],
         [84, 90, 36],
         [10, 84, 33]]]], dtype=int32)]


In [63]:

# Array joining using stack functions (row, column stack)
stacked_3d_axis0 = np.stack(split_3d, axis=0)
stacked_4d_axis0 = np.stack(split_4d, axis=0)

row_stack_3d = np.hstack(array_3d)
row_stack_4d = np.hstack(array_4d)

column_stack_3d = np.vstack(array_3d)
column_stack_4d = np.vstack(array_4d)
print("Stacked 3D Array along axis 0:\n", stacked_3d_axis0)

print("Stacked 4D Array along axis 0:\n", stacked_4d_axis0)


Stacked 3D Array along axis 0:
 [[[[37 79 21]
   [43 83 63]
   [83  5 36]]]


 [[[77 25  5]
   [22  2 90]
   [15 54 86]]]


 [[[68 45 70]
   [43  4 71]
   [64  6  6]]]]
Stacked 4D Array along axis 0:
 [[[[[44 82 62]
    [ 4 49 42]
    [ 9 72 78]]

   [[37  6 71]
    [12 75 66]
    [23 79 78]]

   [[42 74 94]
    [61 66 58]
    [37 57 44]]]]



 [[[[15 60 31]
    [54  4 72]
    [16 64 26]]

   [[ 5 79 35]
    [52 32 20]
    [23 88 53]]

   [[71 54  2]
    [84 90 36]
    [10 84 33]]]]]


In [64]:
# Copying a numpy array
copy_3d = np.copy(array_3d)
copy_4d = np.copy(array_4d)

print("Copied 3D Array:\n", copy_3d)
print("Copied 4D Array:\n", copy_4d)

Copied 3D Array:
 [[[37 79 21]
  [43 83 63]
  [83  5 36]]

 [[77 25  5]
  [22  2 90]
  [15 54 86]]

 [[68 45 70]
  [43  4 71]
  [64  6  6]]]
Copied 4D Array:
 [[[[44 82 62]
   [ 4 49 42]
   [ 9 72 78]]

  [[37  6 71]
   [12 75 66]
   [23 79 78]]

  [[42 74 94]
   [61 66 58]
   [37 57 44]]]


 [[[15 60 31]
   [54  4 72]
   [16 64 26]]

  [[ 5 79 35]
   [52 32 20]
   [23 88 53]]

  [[71 54  2]
   [84 90 36]
   [10 84 33]]]]
